### ISSUE TITLE
Chrome extension Icon missing

### ISSUE THREAD

**Issue by ljmsc** [robertknight/passcards#38]
Hi,
when i try to install the chrome extension i got an error:
The Symbol "data/icons/icons-32.png" can not be loaded for Browseraction.
![2015-02-13 09_46_29-passcards - chrome web store](https://cloud.githubusercontent.com/assets/4758361/6184708/b5601cb0-b365-11e4-9cd6-5af8ab6ad3cc.png)

**Comment by robertknight** [comment]
Fixed - thank-you for the report! I'm looking to set up appropriate automated testing to catch this kind of issue in future.
