### ISSUE TITLE
"No encryption keys have been saved" when entering master password

### ISSUE THREAD

**Issue by nekojira** [robertknight/passcards#44]
I use the chrome extension and point passcards to my dropbox sync and it correctly retrieves 1password keychain (along with backups which I think it's unnecessary though)

I select the stored keychain and I'm prompted for my master password, but although I'm sure it's correct, passcard says "No encryption keys have been saved"

The exception thrown  is referenced here but I couldn't make much of it for the moment: 

https://github.com/robertknight/passcards/blob/2d303106859de79cd9c6d1423c9f12b32ba074d1/lib/local_store.ts#L146

**Comment by robertknight** [comment]
Hi @nekojira 

That message might indicate that either passcards wasn't able to fetch the encryption keys needed to decrypt your database from Dropbox or had a problem with the format of the encryptionKeys.js file.

If you go to the Extensions settings page in Chrome and select the option to open up the inspector for the data/background.html page which is the app and go the Resources tab you can inspect the IndexedDB store where passcards keeps the encrypted items and keys and check whether the keys appear there?

![passcards-store-debug](https://cloud.githubusercontent.com/assets/2458/7706824/917f3342-fe44-11e4-94e3-95492effde77.png)

If the keys are not listed, can you try forcing a refresh by clicking the hamburger icon next to the password input field and selecting 'Switch Store', then re-select your store in Dropbox. If you then go to the Network tab for the data/background.html view (same one as shown in the above screenshot), you should see requests to fetch the encryptionKeys.js file and .password.hint file from Dropbox. Can you check whether both of those are requested successfully? If they are, can you check the IndexedDB storage again afterwards and check if the keys show up?

**Comment by nekojira** [comment]
no, there are no keys in resources
I tried to switch store and reassign it, clicking on the same or by connecting again to Dropbox 
but it's not connecting to Dropbox either (no requests being made shown in network)
I also tried removing and reinstalling passcards, it didn't change

**Comment by nekojira** [comment]
there are no errors in console, so I'm not sure, could it depend that I have 2 factor auth on Dropbox? nevertheless passcards can connect to Dropbox and fetch the key files (including backups)

**Comment by robertknight** [comment]
> nevertheless passcards can connect to Dropbox and fetch the key files (including backups)

Do you mean that it lists your 1Password vaults after selecting 'Connect to Dropbox' and signing in? Do you see a network request for that in the Network tab afterwards? The request would show up as '?access_token=...' in the main list in the Network tab and the full Request URL will start with like 'https://api2.dropbox.com/1/search/auto/'

In the Resources tab, if you go to Local Storage -> chrome-extension://olcd... there will be a key named 'passcards-settings' that should have the ID of your Dropbox account and the path to the folder within in. Could you copy and paste that in here? (There are no access tokens in those settings, just the Dropbox account ID and path within Dropbox).

> there are no errors in console, so I'm not sure, could it depend that I have 2 factor auth on Dropbox? 

I'd hope that apps using the Dropbox API are not affected by whether you have 2-factor auth enabled but I'll check this just in case something is different. If the app is able to search your Dropbox folder for .agilekeychain databases I'd expect it should be able to fetch them.

Can you also confirm which version of Chrome you are using?

**Comment by nekojira** [comment]
Sorry my 2nd comment maybe was misleading. By "fetch the key files" I really meant the list of agilebits keychains - the main one and the backups. I select the main one and the I'm prompted for the master password, and I get the exception thrown. 

Actually I did it wrong! - I wasn't seeing anything because I clicked on the chrome tools on the settings area, instead I had to activate the chrome dev tools by clicking on the passcards popup (sorry didn't think of that). It doesn't have to be from the extensions page in Chrome settings, can be from any tab. Google will open another popup with the Dev tools relevant to passcode extension.

This is what I see:

![screenshot from 2015-05-19 18 37 52](https://cloud.githubusercontent.com/assets/1227930/7708481/45ca45a6-fe56-11e4-840b-2fcd9e4d395c.png)

keys and items are empty

I'm using Ubuntu 15.04
Chrome is 42.0.2311.152 (64bit)

**Comment by robertknight** [comment]
Oh, sorry - I didn't make it clear above which inspector to show. There is actually another one which I didn't highlight properly in the screenshot above. At the bottom of the "Passcards" section in the extensions list there is an "Inspect views" line with a "data/background.html" link. That link shows the Inspector for the actual Passcards app. Can you click on that and check the Network tab. In the screenshot you posted above, the account keys appear under the "Local Storage" rather than "Session Storage" sections.

Chrome extensions with popups are divided into two parts - the popup panel page which is only loaded when you click on the extension's icon, and the 'background' page which runs all the time. The 'background' page is where most of the app's code lives in the case of Passcards and where all of the logic for syncing with Dropbox lives. The popup panel only renders the UI.

**Comment by nekojira** [comment]
I didn't see that because you need developer mode turned on :) I don't do Chrome extensions so I had that turned off

now it's all clear and I can see the errors

![test](https://cloud.githubusercontent.com/assets/1227930/7709382/f935a4cc-fe5c-11e4-9bc8-dbdacfbf7e0d.png)

**Comment by robertknight** [comment]
There might be something about the structure of your vault that is different than the ones I tested with. In your vault do you have a data/default/encryptionKeys.js and data/default/contents.js files? What is the path to the .agilekeychain folder in your vault?

**Comment by nekojira** [comment]
I store my 1Password data in `/folder1/folder2/1Password.agilekeychain`

in `1Password.agilekeychain` there is `/data/default`, inside there is the encyptionKeys.js

I realized that the 1PasswordAnywhere html tool was not functioning, so I followed these instructions: 

https://guides.agilebits.com/1password-mac-kb/5/en/topic/key-data-file-could-not-be-loaded

as well as an advice from AgileBits to enter a new masterpassword to restore the files in place

however, now 1PasswordAnywhere works, but passcards still doesn't (tried to uninstall and reinstall the extension after all the fiddling)

by this point I noticed thought that the requests point to 

`1Password.agilekeychain/data/default/.password.hint?access_token=...`

.password.hint doesn't exist and it is indeed a 404

**Comment by robertknight** [comment]
If you create that file (it is just a one line plain text file with a hint for your password), does that resolve the problem? Passcards doesn't currently handle the case where the encryption keys exist but the hint text file doesn't. if that's the problem it should be straightforward to fix.

**Comment by nekojira** [comment]
I did't know about the hint file - is it something that is normally set from the 1password app? what should the file contain?

**Comment by robertknight** [comment]
Yes. Normally 1Password asks for a password hint when you set your master password. Whatever text you enter (eg. Bad example: "first pet's name") is saved into the .password.hint file, as just plain text.

**Comment by nekojira** [comment]
Apparently setting an hint from the 1Password app is a Mac only feature argh.
I don't have a Mac with me right now to do this.

Perhaps I can try creating the file manually? is it encrypted? or just a string? any text or a json object?

thanks

**Comment by nekojira** [comment]
ohh it works at last! I managed by clearing passcards cache and restarting chrome :)

seem like we have a lot of wiki troubleshooting material in this ticket

**Comment by robertknight** [comment]
Thanks for testing! - I'll leave this open as a task to make sure that any errors syncing encryption keys are shown in the UI and to gracefully handle missing .password.hint files.
