### ISSUE TITLE
Unable to delete sections or fields in firefox

### ISSUE THREAD

**Issue by AlexanderGalen** [robertknight/passcards#47]
The "Delete" button when editing an item just doesn't do anything in firefox. Both the extension and the web app didn't work. I tried in chrome and it worked though. Again, both the extension and the web app.

Also, there's no option to delete a section in the CLI as far as I can tell, otherwise I would've just used that.

**Comment by robertknight** [comment]
Which OS and Firefox version are you using? I'm not able to reproduce the problem with the web app under Ubuntu but I do recall running into some input bugs with the Firefox extension under Mac in the past.

**Comment by AlexanderGalen** [comment]
Running Mac OSX 10.10.4, Firefox 39.0. Same thing goes for the reveal button for passwords as well. Works in Chrome, doesn't in Firefox.

**Comment by robertknight** [comment]
Ah, thought it might be OS X specific. I won't have access to a Mac for testing until I'm back in the UK next week. Are there any errors in the console in Firefox when invoking the Reveal / Delete buttons within the web app version?

**Comment by AlexanderGalen** [comment]
Nope, not seeing any errors for the reveal or delete buttons.

**Comment by robertknight** [comment]
I can reproduce the problem with current Firefox Nightlies on OS X. Issue affects all of the field action buttons (Copy, Reveal, Delete, Generate)

**Comment by robertknight** [comment]
This is due to the `<button>` element not receiving a focus event in OS X at least when clicked. When clicking outside of a field's text, the `<input>` loses focus and the element that gains focus is the details view form. Since that is outside of the active field, the app hides the action buttons for the field.

See difference between Chrome and Firefox/Safari when clicking between text input and button in:

```html
<input id="foobar">
<button>Click me</button>
<script>
	document.addEventListener('focus', function (e) {
		console.log(e.target, 'gained focus');
	}, true);
	document.addEventListener('blur', function (e) {
		console.log(e.target, 'lost focus');
	}, true);
</script>
```
