### ISSUE TITLE
Passcards fails to decrypt Agile Keychain .1password items without securityLevel field

### ISSUE THREAD

**Issue by robertknight** [robertknight/passcards#57]
@asbjornenge reported an issue where Passcards fails to sync items which do not have an `securityLevel` field in their .1password files.

The items in question have this structure:

```js
{
   "encrypted" : "...",
   "locationKey" : "<URL>",
   "uuid" : "...",
   "keyID" : "...",
   "typeName" : "webforms.WebForm",
   "title" : "...",
   "updatedAt" : <timestamp>,
   "openContents" : {
      "usernameHash" : "...",
      "contentsHash" : "..."
   },
   "createdAt" : <timestamp>,
   "location" : "..."
}
```

There is no `securityLevel` field but there is a `keyID` field which maps to the `identifier` attribute in the `encryptionKeys.js` file.

**Comment by robertknight** [comment]
You can test a version of the CLI app with this fix using `npm install -g passcards@gh57`. The browser extensions should be updated shortly.

**Comment by asbjornenge** [comment]
@robertknight :tada: works like a charm!! :heart_eyes_cat:
