### ISSUE TITLE
Sign Firefox Add-on

### ISSUE THREAD

**Issue by aaronraimist** [robertknight/passcards#60]
The Firefox add-on needs to be signed so it can continue to be installed in upcoming versions of Firefox.

https://blog.mozilla.org/addons/2015/02/10/extension-signing-safer-experience/
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox
https://wiki.mozilla.org/Addons/Extension_Signing#Timeline

**Comment by robertknight** [comment]
Thanks for the heads-up. Something important missing last I looked was an API for the extension signing service. The build and deployment for Passcards is entirely automated. For Chrome, there is a script which publishes to the store using the Chrome Extension store APIs.

I think I read somewhere that AdBlock Plus is currently using Selenium or a similar browser testing/automation tool for this. Not pretty, but it works.

**Comment by aaronraimist** [comment]
I don't know of any API that would allow the process to be entirely automated but the review process is also slightly different than Chrome if I understand correctly. Every update of a Firefox add-on goes through a manual review process so it is likely to always be a few days behind an automated Chrome extension release anyway. I would be willing to post new versions to Mozilla within a one or two days of a change being made.

**Comment by robertknight** [comment]
> I don't know of any API that would allow the process to be entirely automated
> but the review process is also slightly different than Chrome if I understand correctly

As I understand it, the manual review process in the past was partly down to Firefox addons essentially having unfettered access to the browser and also I think partly down to different expectations about what was an acceptable speed for delivery of updates. Chrome changed those expectations and Mozilla are adapting.

Also, Passcards' build and deployment is entirely automated - I push changes to master and the Firefox and Chrome extensions, web app and command-line app are all published a short a few minutes later. Together with the entire thing being written in JS and sharing as much code as possible between versions, this is important to make it possible to ship a useful app with far fewer resources than commercial alternatives.

**Comment by aaronraimist** [comment]
I understand that everything is automated now but until Mozilla creates this API, updates to the Firefox add-on are going to be significantly behind that of the Chrome add-on. I think you should at least publish it manually for now because in one month no one will be able to install Passcards (anyone who runs a nightly version of Firefox, like me, hasn't been able to install Passcards for a while).

Again, I would be willing to upload new versions of Passcards to AMO for you if you would like.

**Comment by robertknight** [comment]
@aaronraimist - I agree and thanks for the offer. A first step will be to get the extension to a point where it validates at least the checks required for automated signing on AMO, which are less strict than those required for manual review.

I've not submitted a recent build to AMO myself so I don't know how many issues that will flag up.

**Comment by aaronraimist** [comment]
See this discourse post for more information from Andreas Wagner: https://discourse.mozilla-community.org/t/upload-an-add-on-update-via-api/5034

It lists a Mozilla bug and some GitHub issues so you can track the progress of implementing the API.

For now you can upload it manually or use something like this: https://github.com/minj/foxtrick/blob/master/maintainer/dist/amo_upload.py (found in https://github.com/mozilla/shumway/issues/2329) or use the Adblock Plus code: https://adblockplus.org/blog/adblock-plus-for-firefox-and-element-hiding-helper-development-builds-now-hosted-on-amo that you mentioned earlier.

**Comment by aaronraimist** [comment]
@robertknight Have you submitted a build to AMO yet? If you would like, I can submit a build and [set you as the owner](https://developer.mozilla.org/en-US/Add-ons/Distribution#Ownership) so the review can get started.

**Comment by robertknight** [comment]
@aaronraimist - I haven't submitted a build to AMO yet and if you could that would be much appreciated. Thanks.

**Comment by aaronraimist** [comment]
@robertknight I submitted an initial build to AMO. It is currently 12 of 12 in the queue for a preliminary review. I'll post my changes to a fork of this code soon.

**Comment by aaronraimist** [comment]
```
Your version was rejected because of the following problems:

1)  Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.

Alternatives are available for most use cases. See https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions/XUL_School/Appendix_C:_Avoid_using_eval_in_Add-ons for more information.

2) In order to prevent vulnerabilities, the `setTimeout` and `setInterval` functions should be called only with function expressions as their first argument. If you are passing a function which is not being correctly detected as such, please consider passing a closure or arrow function, which in turn calls the original function.

Please fix them and submit again. Thank you.
```

**Comment by robertknight** [comment]
_Sighs_ - To the best of my knowledge, all of the warnings about `setTimeout()` are spurious. That is, in the context of Chrome or a normal web page, CSP could be used to make any uses of `setTimeout(<code>)` or `eval()` fail as runtime errors instead of being security hazards and indeed that is how Chrome deals with the issue. Is it possible to do the same for addons or any idea if that is in the pipeline as part of web extensions?

**Comment by robertknight** [comment]
I should add that all of the flagged code runs in the context of a popup panel which appears when clicking on the app's icon - so it doesn't need access to any Firefox-specific APIs, except the message port that is used to communicate with the addon's main source file in order to determine the current tab's URL and route messages between the tab's content script and the panel.

**Comment by robertknight** [comment]
https://blog.mozilla.org/addons/2015/11/20/signing-api-now-available/

**Comment by robertknight** [comment]
Thanks to @dstillman , the Firefox addon team have been persuaded to drop the requirement that addons pass their validator and there are now tools and APIs to automatically sign Firefox addons. I've successfully created a signed version of Passcards locally.

There is some remaining work to do but it looks like all the hard parts have been sorted out now.
