### ISSUE TITLE
Can't run passcards cli

### ISSUE THREAD

**Issue by aaronraimist** [robertknight/passcards#73]
Every time I run any passcards command I get this error message:

```
/usr/local/lib/node_modules/passcards/passcards:15
app.exec(commandArgs).then(status => {
                                  ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

OS: Xubuntu 16.10

**Comment by robertknight** [comment]
Hello Aaron,

The error message is complaining about lack of support for newer JavaScript syntax in the version of Node you are using. The current version of Passcards requires Node v6 or later.

Are you using the version of Node that comes with Xubuntu 16.10? I must admit I hadn't considered that Ubuntu are still shipping a relatively old version of Node when I made that change.

**Comment by aaronraimist** [comment]
Seems like Xubuntu 16.10 ships with Node v4.2.6. I successfully installed v6.9.2 using NVM and everything seems to work now. Thanks. You might want to add that requirement to the website: https://robertknight.github.io/passcards/
