### ISSUE TITLE
Dropbox: Account Link: In Review

### ISSUE THREAD

**Issue by drewrothstein** [robertknight/passcards#74]
Receiving this message after installing the Google Chrome Extension and trying to link a Dropbox account:
```    
This app is unable to link additional users because it has been frozen pending review.
```
This message comes from Dropbox it appears and it is post-authentication with them.

**Comment by robertknight** [comment]
Hello @drewrothstein 

Thank-you for the report. Passcards reached the limit for unreviewed clients using the API. I'll get this fixed. In the meantime if anyone wishes new to use the app with Dropbox they will have to register a new API client (see https://www.dropbox.com/developers/apps) to get an API key and replace the one hardcoded in the source at https://github.com/robertknight/passcards/blob/master/lib/vfs/dropbox.ts#L5

**Comment by drselump14** [comment]
Hi, I've tried to set my dropbox API but this error appeared when I connect to dropbox
`Invalid redirect_uri. It must exactly match one of the redirect URIs you've pre-configured for your app`

Which redirect uri I should set?

**Comment by drselump14** [comment]
Oh, it's http://localhost:8000/webui/index.html ... sorry
